--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/bbo51dog/PMDiscordAPI
build-by-default: true
branches:
- master
projects:
  PMDiscordAPI:
    path: ""
  LibPMDiscordAPI:
    path: ""
    type: library
    model: virion
...
